//! Names available without imports: the std prelude, primitives, built-in attributes.

/// Type-namespace prelude names and their canonical paths.
pub(crate) const PRELUDE_TYPES: &[(&str, &str)] = &[
    ("Option", "std::option::Option"),
    ("Result", "std::result::Result"),
    ("Vec", "std::vec::Vec"),
    ("String", "std::string::String"),
    ("Box", "std::boxed::Box"),
    ("ToString", "std::string::ToString"),
    ("ToOwned", "std::borrow::ToOwned"),
    ("Clone", "std::clone::Clone"),
    ("Copy", "std::marker::Copy"),
    ("Send", "std::marker::Send"),
    ("Sync", "std::marker::Sync"),
    ("Sized", "std::marker::Sized"),
    ("Unpin", "std::marker::Unpin"),
    ("Drop", "std::ops::Drop"),
    ("Fn", "std::ops::Fn"),
    ("FnMut", "std::ops::FnMut"),
    ("FnOnce", "std::ops::FnOnce"),
    ("Iterator", "std::iter::Iterator"),
    ("IntoIterator", "std::iter::IntoIterator"),
    ("Extend", "std::iter::Extend"),
    ("FromIterator", "std::iter::FromIterator"),
    ("DoubleEndedIterator", "std::iter::DoubleEndedIterator"),
    ("ExactSizeIterator", "std::iter::ExactSizeIterator"),
    ("PartialEq", "std::cmp::PartialEq"),
    ("Eq", "std::cmp::Eq"),
    ("PartialOrd", "std::cmp::PartialOrd"),
    ("Ord", "std::cmp::Ord"),
    ("Default", "std::default::Default"),
    ("From", "std::convert::From"),
    ("Into", "std::convert::Into"),
    ("AsRef", "std::convert::AsRef"),
    ("AsMut", "std::convert::AsMut"),
    ("TryFrom", "std::convert::TryFrom"),
    ("TryInto", "std::convert::TryInto"),
    ("Debug", "std::fmt::Debug"),
    ("Hash", "std::hash::Hash"),
    ("Future", "std::future::Future"),
    ("IntoFuture", "std::future::IntoFuture"),
];

/// Value-namespace prelude names: `(name, owner path, variant or function name)`.
pub(crate) const PRELUDE_VALUES: &[(&str, &str, &str)] = &[
    ("Some", "std::option::Option", "Some"),
    ("None", "std::option::Option", "None"),
    ("Ok", "std::result::Result", "Ok"),
    ("Err", "std::result::Result", "Err"),
    ("drop", "std::mem", "drop"),
];

/// Macros from std that need no import.
pub(crate) const PRELUDE_MACROS: &[&str] = &[
    "assert",
    "assert_eq",
    "assert_ne",
    "cfg",
    "column",
    "compile_error",
    "concat",
    "dbg",
    "debug_assert",
    "debug_assert_eq",
    "debug_assert_ne",
    "env",
    "eprint",
    "eprintln",
    "file",
    "format",
    "format_args",
    "include",
    "include_bytes",
    "include_str",
    "line",
    "matches",
    "module_path",
    "option_env",
    "panic",
    "print",
    "println",
    "stringify",
    "thread_local",
    "todo",
    "unimplemented",
    "unreachable",
    "vec",
    "write",
    "writeln",
];

/// Derive macro names from std and the trait each one implements.
pub(crate) const STD_DERIVES: &[(&str, &str)] = &[
    ("Debug", "std::fmt::Debug"),
    ("Clone", "std::clone::Clone"),
    ("Copy", "std::marker::Copy"),
    ("PartialEq", "std::cmp::PartialEq"),
    ("Eq", "std::cmp::Eq"),
    ("PartialOrd", "std::cmp::PartialOrd"),
    ("Ord", "std::cmp::Ord"),
    ("Hash", "std::hash::Hash"),
    ("Default", "std::default::Default"),
];

pub(crate) const PRIMITIVES: &[&str] = &[
    "i8", "i16", "i32", "i64", "i128", "isize", "u8", "u16", "u32", "u64", "u128", "usize", "f32",
    "f64", "bool", "char", "str",
];

/// Attributes understood by the compiler or standard tools; they never resolve to an item.
pub(crate) const BUILTIN_ATTRIBUTES: &[&str] = &[
    "allow",
    "automatically_derived",
    "bench",
    "cfg",
    "cfg_attr",
    "cold",
    "crate_name",
    "crate_type",
    "deny",
    "deprecated",
    "derive",
    "doc",
    "expect",
    "export_name",
    "feature",
    "forbid",
    "global_allocator",
    "ignore",
    "inline",
    "link",
    "link_name",
    "link_section",
    "macro_export",
    "macro_use",
    "must_use",
    "no_implicit_prelude",
    "no_link",
    "no_main",
    "no_mangle",
    "no_std",
    "non_exhaustive",
    "panic_handler",
    "path",
    "proc_macro",
    "proc_macro_attribute",
    "proc_macro_derive",
    "recursion_limit",
    "repr",
    "should_panic",
    "target_feature",
    "test",
    "track_caller",
    "type_length_limit",
    "used",
    "warn",
    "windows_subsystem",
];

pub(crate) const EXTERN_PRELUDE_CRATES: &[&str] = &["std", "core", "alloc", "proc_macro"];
